name: ci-cd
on:
    push:
        branches: ["main"]
    workflow_dispatch:
jobs:
    ci:
        runs-on: ubuntu-lastest
        steps:
            - name: Otendo o Código
              uses: actiond/checkout@v4.1.5
            - name: Autentificação no Docker Hub
              uses: docker/login-action@v3.1.0
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }} 
          
        
